### ISSUE TITLE
Run inference.ipynb and get "ValueError: Received incompatible devices for jitted computation..."

### ISSUE THREAD

**Issue by ruizhaogit** [Physical-Intelligence/openpi#261]
Hello,

Thank you for open sourcing the great work!

I run example/inference.ipynb and get the following error on a machine with two A6000 GPUs:

"ValueError: Received incompatible devices for jitted computation. Got argument args[0] of conv_general_dilated with shape float32[2,224,224,3] and device ids [0] on platform GPU and argument args[1] of conv_general_dilated with shape float32[14,14,3,1152] and device ids [0, 1] on platform GPU"

Does anyone know how to solve this?

Thanks,
Rui

**Comment by endic-sam928281** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the Pi0FAST class to use jax.device_put for consistent device placement of model parameters and inputs. This should resolve the ValueError caused by incompatible devices for jitted computation.

You can review changes in this commit: https://github.com/endic-sam928281/Physical-Intelligence-openpi-261/commit/9f7d031ca838afb547a20fa2e77d88a9b6f08182.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ruizhaogit** [comment]
I tried the suggestion from Indic-sam928281 and get the following error:

"import openpi.models.pi0_fast as pi0_fast

  File openpi/src/openpi/models/pi0_fast.py:147
    _gemma.Module(
    ^
SyntaxError: invalid syntax. Perhaps you forgot a comma?"

**Comment by ruizhaogit** [comment]
Adding the following two lines at the top of inference.ipynb solves the problem.
"import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0""

**Comment by uzhilinsky** [comment]
This is because the model expects data parallel sharding but the data loader is currently using a single device sharding by default. I'll send a PR to adjust the default inside the data loader.
